### ISSUE TITLE
Issue with num_threads in walkthrough

### ISSUE THREAD

**Issue by PeetoomHeida** [StanJulia/Stan.jl#112] opened 2022-01-30 19:27 UTC
Hello,

I am new to Stan and Julia, but have been trying to get them to work. it took me a while to get everything configured, but when I run the example at  ```Stan.jl/docs/src/WALKTHROUGH.md``` I have to modify the script to include a ```num_threads=1``` argument in the ```stan_sample()``` call. Perhaps I should have known better in setting up Julia to ensure it had multi-threading enabled, but I think either making an this multi-threading an explicit requirement, or modifying the script so it works out of the box might make the walk-through a little more seamless for new users.

**Comment by goedman** [comment] 2022-01-30 20:47
Hi Isaac (@PeetoomHeida), you've just tried this at a time I'm doing a major update to support C++ threads. In about an hour I hope to have this work completed, an issue is that Stan.jl has to be the last package I can update as it tests all other packages.

Which package versions have you installed? ( `] status` ) should show the list.

Stan.jl v9.0.0 expects StanSample.jl v6.0.1 and v4 for all other Stan....jl packages (StanOptimize, StanQuap, StanDiagnose and StanVariational).

By WALKTHROUGH.md you mean a derived .jl  script like below?
```
using StanSample, DataFrames
model = "
data { 
  int<lower=0> N; 
  int<lower=0,upper=1> y[N];
} 
parameters {
  real<lower=0,upper=1> theta;
} 
model {
  theta ~ beta(1,1);
    y ~ bernoulli(theta);
}
";
sm = SampleModel("bernoulli", model);
data = Dict("N" => 10, "y" => [0, 1, 0, 1, 0, 0, 0, 0, 0, 1]);
rc = stan_sample(sm; data);
if success(rc)
  df = read_samples(sm, :dataframe);
  df |> display
end
```

I'll add that to the walkthrough directory.

**Comment by goedman** [comment] 2022-01-30 20:58
OK, Stan.jl v9 just got merged.

You are definitely right in that handling the C++ thread capabilities is not a simple issue, but it should work now (I hope!).

If above script does not run for you, can you send me the `Pkg.status()` output and the error messages you receive. That will help a lot.

Thanks for sticking with this.

**Comment by goedman** [comment] 2022-01-30 21:58
Re-reading your post I noticed the part "I have to modify the script to include a num_threads=1". This might also be caused by the cmdstan binary not supporting threads. If that is the case it should also work if you set:
```
rc = stan_sample(model; num_chains=4, data)
```
Currently, if num_chains > 1, i.e. you request the chains to execute on Julia level, num_threads should not have been part of the invocation of cmdstan. The invocation lines can be inspected by:
```
sm.cmds[1]
```
in above (edited) script. It should look like:
```
julia> sm.cmds[1]
`/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_JUIOJ3/bernoulli sample num_chains=1 num_samples=1000 num_warmup=1000 save_warmup=0 thin=1 adapt engaged=1 gamma=0.05 delta=0.8 kappa=0.75 t0=10 init_buffer=75 term_buffer=75 window=25 algorithm=hmc engine=nuts max_depth=10 metric=diag_e stepsize=1.0 stepsize_jitter=0.0 random seed=-1 init=2 id=1 data file=/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_JUIOJ3/bernoulli_data_1.json output file=/var/folders/l7/pr04h0650q5dvqttnvs8s2c00000gn/T/jl_JUIOJ3/bernoulli_chain_1.csv refresh=100`
```

Anyway, I'll stop here. I edited above script and inserted the `num_chains=4` in the call to `stan_sample()`.

**Comment by PeetoomHeida** [comment] 2022-04-04 03:17
Thanks so much for your help!

**Closed** 2022-04-04 03:17 UTC
